# Generated by Django 5.0.4 on 2024-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('LP', 'Laptops'), ('EP', 'Earphones'), ('CM', 'Cameras'), ('TV', 'TV Monitors'), ('MP', 'Mobile Phones'), ('PL', 'Playstations')], max_length=2),
        ),
    ]
