# Generated by Django 5.0.4 on 2024-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0006_alter_orderplaced_status_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptops'), ('EP', 'Earphones'), ('CM', 'Cameras'), ('TV', 'TV Monitors'), ('MP', 'Mobile Phones'), ('SP', 'Speakers')], max_length=2),
        ),
    ]
